---
title: "Posts"
site: distill::distill_website
listing: posts
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(LSDinterface)
library(tidyverse)
library(forecast)
library(ggthemes)
```

<h1 style="font-size: 300%; text-align: center; font-family: optima;">Macroeconomia <br><br> Baseada em Agentes</h1>

<br>

```{r title-page-plot, layout="l-page", eval=T, fig.width=15, fig.asp=.25}
# Acessar resultados do LSD
capa <- read.raw.lsd("capa.res.gz")

# Mudar nome das Variáveis (Colunas)
colnames(capa) <- 1:3

# Acrescentar t_0
capa <- capa %>%
  as_tibble() %>%
  ts()

# Visualizar Gráfico
autoplot(capa) +
  ggtitle("") +
  xlab("") +
  ylab("") +
  theme_hc() +
  theme(plot.title = element_text(size = 15, hjust = 0.5, colour = "black"),
        plot.subtitle = element_text(size = 10, hjust = 0.5, colour = "black"),
        legend.position = "none") +
  scale_colour_brewer(direction = 1, type = "qual", palette = 2) +
  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL)
```
